import { defineTheme, defaultTypography, themeTimestamp } from './_shared';

export const blueHourCinema = defineTheme({
  id: 'blue-hour-cinema',
  name: 'Blue Hour Cinema',
  shortDescription: 'Human cinematic twilight between day and night.',
  emotionalTone: 'Melancholic, beautiful, calm, premium.',
  designKeywords: ['blue hour', 'cinematic', 'human layer', 'soft vignette', 'reflective'],
  source: 'built-in',
  colors: {
    bg: '#07101c',
    bgSecondary: '#111a2a',
    surface: '#172235',
    surfaceElevated: '#1f2d44',
    text: '#f0f6ff',
    textSecondary: '#c2cde0',
    textMuted: '#8794aa',
    accent: '#6aa9ff',
    accentSecondary: '#9ee8ff',
    accentEmotional: '#d3a6ff',
    accentProof: '#ff7b75',
    border: '#2b3a52',
    borderSubtle: '#1d2a3e',
    borderStrong: '#49617e',
    glow: '#9ee8ff',
    warning: '#f0c36c',
    success: '#90e0bf',
    selection: '#9ee8ff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 650,
    bodyWeight: 400,
    lineHeight: 1.76,
    typeLg: '1.625rem',
    type2xl: 'clamp(2.65rem, 5.6vw, 5rem)',
    typeDisplay: 'clamp(4.2rem, 10.4vw, 8.6rem)',
  },
  spacing: {
    baseUnit: 8,
    sectionY: '144px',
    containerX: 'clamp(24px, 7vw, 104px)',
    cardPadding: '30px',
    gridGap: '22px',
    density: 'cinematic',
  },
  radius: { xs: '3px', sm: '6px', md: '10px', lg: '18px', card: '8px', button: '6px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #9ee8ff', dividerOpacity: 0.58 },
  elevation: {
    ambient: '0 24px 96px color-mix(in srgb, #07101c 70%, transparent)',
    raised: '0 32px 120px color-mix(in srgb, #6aa9ff 14%, transparent)',
    glow: '0 0 54px color-mix(in srgb, #9ee8ff 18%, transparent)',
    inset: 'inset 0 1px 0 color-mix(in srgb, #f0f6ff 6%, transparent)',
    card: '0 22px 72px color-mix(in srgb, #07101c 46%, transparent)',
  },
  background: {
    type: 'blue-hour',
    dotSize: 0.9,
    dotSpacing: 44,
    dotOpacity: 0.045,
    dotRevealOpacity: 0.08,
    dotFieldOpacity: 0.32,
    radialGlowColor: '#9ee8ff',
    radialGlowOpacity: 0.08,
    radialGlowSize: 38,
    radialGlowBlur: 72,
    radialGlowColor2: '#d3a6ff',
    radialGlowOpacity2: 0.08,
    noiseOpacity: 0.02,
    vignetteOpacity: 0.74,
    animationSpeed: 76,
    animationIntensity: 0.52,
    scanlineOpacity: 0,
    skylineOpacity: 0.05,
    textureOpacity: 0.03,
  },
  glow: { primary: '#6aa9ff', secondary: '#9ee8ff', intensity: 0.78, blur: '72px', spread: '38vmax' },
  motion: {
    personality: 'cinematic',
    revealType: 'fadeIn',
    revealDuration: 740,
    hoverDuration: 150,
    transitionDuration: 340,
    complexDuration: 500,
    easingEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
    easingExit: 'cubic-bezier(0.7, 0, 0.84, 0)',
    easingState: 'cubic-bezier(0.22, 1, 0.36, 1)',
    parallaxIntensity: 0.06,
    ambientMotionIntensity: 0.7,
  },
  components: {
    cardStyle: 'quiet-luxury',
    buttonStyle: 'luxury',
    navStyle: 'sticky-glass',
    caseFileStyle: 'quiet-luxury',
    badgeStyle: 'cinema-caption',
    inputStyle: 'soft-console',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 70%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-default) 68%, transparent)',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 74%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 24%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 45%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 76%, transparent)',
  },
  layout: {
    density: 'cinematic',
    maxContentWidth: '1288px',
    sectionPaddingTop: '144px',
    sectionPaddingBottom: '144px',
    cardPadding: '30px',
    gridGap: '22px',
    borderRadius: '8px',
    panelBlur: 24,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '86px',
    twelveColumnGap: '22px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'reflective blue-hour portrait scene', intensity: 1, backgroundIntensity: 0.92 },
    human: { mood: 'quiet emotional weather', intensity: 1, backgroundIntensity: 0.96, accent: '#d3a6ff' },
    contact: { mood: 'calm final frame', intensity: 0.84, backgroundIntensity: 0.82 },
  },
  preview: {
    vibeLabel: 'Human cinema',
    bestFor: 'Storytelling and human layer',
    densityLabel: 'Cinematic',
    motionLabel: 'Slow atmospheric',
    swatches: ['#07101c', '#1f2d44', '#6aa9ff', '#d3a6ff', '#f0f6ff'],
    gradient: 'radial-gradient(circle at 30% 22%, #283d67 0%, #111a2a 48%, #07101c 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});

