import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const cosmicDebug = defineTheme({
  id: 'cosmic-debug',
  name: 'Cosmic Debug',
  shortDescription: 'Debugging reality from a cosmic control room.',
  emotionalTone: 'Mysterious, futuristic, slightly strange, intelligent.',
  designKeywords: ['cosmic control room', 'debug traces', 'purple-blue', 'unknowns', 'console metadata'],
  source: 'built-in',
  colors: {
    bg: '#040317',
    bgSecondary: '#0b0924',
    surface: '#121033',
    surfaceElevated: '#1a1644',
    text: '#f2f0ff',
    textSecondary: '#bbb5dc',
    textMuted: '#827aa5',
    accent: '#6c7cff',
    accentSecondary: '#6ff4ff',
    accentEmotional: '#c26bff',
    accentProof: '#ff5ca8',
    border: '#29265c',
    borderSubtle: '#1c1a42',
    borderStrong: '#4d48a4',
    glow: '#6ff4ff',
    warning: '#ffd166',
    success: '#77f0cb',
    selection: '#c26bff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 700,
    bodyWeight: 400,
    lineHeight: 1.62,
    typeLg: '1.5rem',
    type2xl: 'clamp(2.5rem, 5.4vw, 4.8rem)',
    typeDisplay: 'clamp(4rem, 10.8vw, 8.8rem)',
  },
  typographySystem: getTypographySystemForTheme('cosmic-debug'),
  spacing: {
    baseUnit: 8,
    sectionY: '124px',
    containerX: 'clamp(24px, 6.4vw, 96px)',
    cardPadding: '26px',
    gridGap: '18px',
    density: 'cinematic',
  },
  radius: { xs: '2px', sm: '5px', md: '10px', lg: '18px', card: '5px', button: '4px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #6ff4ff', dividerOpacity: 0.68 },
  elevation: {
    ambient: '0 18px 86px color-mix(in srgb, #040317 76%, transparent)',
    raised: '0 28px 120px color-mix(in srgb, #6c7cff 17%, transparent)',
    glow: '0 0 60px color-mix(in srgb, #c26bff 24%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #6ff4ff 7%, transparent)',
    card: '0 20px 80px color-mix(in srgb, #040317 52%, transparent)',
  },
  background: {
    type: 'cosmic-debug',
    dotSize: 1.1,
    dotSpacing: 26,
    dotOpacity: 0.095,
    dotRevealOpacity: 0.18,
    dotFieldOpacity: 0.72,
    radialGlowColor: '#6ff4ff',
    radialGlowOpacity: 0.09,
    radialGlowSize: 36,
    radialGlowBlur: 60,
    radialGlowColor2: '#c26bff',
    radialGlowOpacity2: 0.13,
    noiseOpacity: 0.03,
    vignetteOpacity: 0.86,
    animationSpeed: 50,
    animationIntensity: 1.1,
    scanlineOpacity: 0.025,
    skylineOpacity: 0,
    textureOpacity: 0.04,
  },
  glow: { primary: '#6c7cff', secondary: '#c26bff', intensity: 1.2, blur: '60px', spread: '36vmax' },
  motion: {
    personality: 'cosmic',
    revealType: 'translateY',
    revealDuration: 620,
    hoverDuration: 120,
    transitionDuration: 260,
    complexDuration: 460,
    easingEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
    easingExit: 'cubic-bezier(0.7, 0, 0.84, 0)',
    easingState: 'cubic-bezier(0.22, 1, 0.36, 1)',
    parallaxIntensity: 0.12,
    ambientMotionIntensity: 1.15,
  },
  components: {
    cardStyle: 'cosmic',
    buttonStyle: 'cosmic',
    navStyle: 'sticky-glass',
    caseFileStyle: 'cosmic',
    badgeStyle: 'debug-chip',
    inputStyle: 'cosmic-console',
    cardBackground: 'linear-gradient(145deg, color-mix(in srgb, var(--surface-card) 84%, transparent), color-mix(in srgb, var(--accent-emotional) 10%, transparent))',
    cardBorder: 'color-mix(in srgb, var(--accent-emotional) 20%, var(--line-default))',
    cardHoverBackground: 'linear-gradient(145deg, color-mix(in srgb, var(--surface-raised) 86%, transparent), color-mix(in srgb, var(--accent-secondary) 8%, transparent))',
    buttonBackground: 'color-mix(in srgb, var(--accent-emotional) 22%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 50%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 80%, transparent)',
  },
  layout: {
    density: 'cinematic',
    maxContentWidth: '1260px',
    sectionPaddingTop: '124px',
    sectionPaddingBottom: '124px',
    cardPadding: '26px',
    gridGap: '18px',
    borderRadius: '5px',
    panelBlur: 20,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '80px',
    twelveColumnGap: '18px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'cosmic console wake sequence', intensity: 1, backgroundIntensity: 1 },
    projects: { mood: 'debug traces through unknown systems', intensity: 0.96, backgroundIntensity: 0.9 },
    philosophy: { mood: 'strange intelligent manifesto', intensity: 0.92, backgroundIntensity: 0.82, accent: '#c26bff' },
  },
  preview: {
    vibeLabel: 'Reality debugger',
    bestFor: 'Experimental identity version',
    densityLabel: 'Cinematic',
    motionLabel: 'Trace drift',
    swatches: ['#040317', '#1a1644', '#6c7cff', '#c26bff', '#6ff4ff'],
    gradient: 'radial-gradient(circle at 35% 25%, #2c276c 0%, #0b0924 48%, #040317 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
