import { defineTheme, defaultTypography, themeTimestamp } from './_shared';

export const editorialCybernetic = defineTheme({
  id: 'editorial-cybernetic',
  name: 'Editorial Cybernetic',
  shortDescription: 'High-fashion editorial layout fused with engineering diagrams.',
  emotionalTone: 'Bold, stylish, sharp, magazine-like, futuristic.',
  designKeywords: ['fashion editorial', 'cybernetic diagrams', 'large type', 'asymmetry', 'thin lines'],
  source: 'built-in',
  colors: {
    bg: '#06060a',
    bgSecondary: '#111118',
    surface: '#15151e',
    surfaceElevated: '#1d1d28',
    text: '#f5f2ed',
    textSecondary: '#c7c1b8',
    textMuted: '#8c8790',
    accent: '#4a8cff',
    accentSecondary: '#e8f7ff',
    accentEmotional: '#b86cff',
    accentProof: '#ff4f6d',
    border: '#30303c',
    borderSubtle: '#20202a',
    borderStrong: '#55515f',
    glow: '#4a8cff',
    warning: '#f4c76c',
    success: '#91e7ba',
    selection: '#b86cff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 700,
    bodyWeight: 400,
    lineHeight: 1.5,
    typeXl: '2.25rem',
    type2xl: 'clamp(3rem, 7vw, 6.4rem)',
    typeDisplay: 'clamp(5rem, 14vw, 11rem)',
  },
  spacing: {
    baseUnit: 8,
    sectionY: '148px',
    containerX: 'clamp(24px, 7.5vw, 112px)',
    cardPadding: '28px',
    gridGap: '18px',
    density: 'editorial',
  },
  radius: { xs: '0px', sm: '2px', md: '4px', lg: '8px', card: '0px', button: '0px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #e8f7ff', dividerOpacity: 0.8 },
  elevation: {
    ambient: '0 20px 82px color-mix(in srgb, #06060a 75%, transparent)',
    raised: '0 28px 108px color-mix(in srgb, #b86cff 12%, transparent)',
    glow: '0 0 42px color-mix(in srgb, #4a8cff 20%, transparent)',
    inset: 'inset 0 1px 0 color-mix(in srgb, #f5f2ed 5%, transparent)',
    card: '0 18px 60px color-mix(in srgb, #06060a 44%, transparent)',
  },
  background: {
    type: 'diagram',
    dotSize: 0.8,
    dotSpacing: 40,
    dotOpacity: 0.055,
    dotRevealOpacity: 0.1,
    dotFieldOpacity: 0.42,
    radialGlowColor: '#4a8cff',
    radialGlowOpacity: 0.07,
    radialGlowSize: 30,
    radialGlowBlur: 52,
    radialGlowColor2: '#b86cff',
    radialGlowOpacity2: 0.08,
    noiseOpacity: 0.02,
    vignetteOpacity: 0.82,
    animationSpeed: 54,
    animationIntensity: 0.58,
    scanlineOpacity: 0.008,
    skylineOpacity: 0,
    textureOpacity: 0.035,
  },
  glow: { primary: '#4a8cff', secondary: '#b86cff', intensity: 0.8, blur: '52px', spread: '30vmax' },
  motion: {
    personality: 'editorial',
    revealType: 'translateY',
    revealDuration: 520,
    hoverDuration: 120,
    transitionDuration: 240,
    complexDuration: 420,
    easingEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
    easingExit: 'cubic-bezier(0.7, 0, 0.84, 0)',
    easingState: 'cubic-bezier(0.22, 1, 0.36, 1)',
    parallaxIntensity: 0.05,
    ambientMotionIntensity: 0.62,
  },
  components: {
    cardStyle: 'editorial',
    buttonStyle: 'editorial',
    navStyle: 'editorial-band',
    caseFileStyle: 'editorial',
    badgeStyle: 'section-number',
    inputStyle: 'diagram-field',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 68%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-strong) 48%, var(--line-default))',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 74%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--text-primary) 8%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 34%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 80%, transparent)',
  },
  layout: {
    density: 'editorial',
    maxContentWidth: '1360px',
    sectionPaddingTop: '148px',
    sectionPaddingBottom: '148px',
    cardPadding: '28px',
    gridGap: '18px',
    borderRadius: '0px',
    panelBlur: 18,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '84px',
    twelveColumnGap: '18px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'oversized editorial identity spread', intensity: 1, backgroundIntensity: 0.86 },
    philosophy: { mood: 'manifesto typography wall', intensity: 1, backgroundIntensity: 0.74, accent: '#e8f7ff' },
    projects: { mood: 'asymmetric systems editorial', intensity: 0.9, backgroundIntensity: 0.72 },
  },
  preview: {
    vibeLabel: 'Magazine cybernetics',
    bestFor: 'Most memorable version',
    densityLabel: 'Editorial',
    motionLabel: 'Type-led reveal',
    swatches: ['#06060a', '#1d1d28', '#f5f2ed', '#4a8cff', '#b86cff'],
    gradient: 'linear-gradient(145deg, #06060a 0%, #15151e 54%, #2a173f 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});

