import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const nocturnalSignal = defineTheme({
  id: 'nocturnal-signal',
  name: 'Nocturnal Signal',
  shortDescription: 'Midnight systems interface with cold blue trace light.',
  emotionalTone: 'Dark, precise, restrained, technical, premium.',
  designKeywords: ['midnight navy', 'cold neon', 'trace IDs', 'quiet rain', 'proof-over-vibes'],
  source: 'built-in',
  colors: {
    bg: '#05070d',
    bgSecondary: '#0b111c',
    surface: '#0d1420',
    surfaceElevated: '#101826',
    text: '#eaf0ff',
    textSecondary: '#aab4c8',
    textMuted: '#758197',
    accent: '#2f6bff',
    accentSecondary: '#5debff',
    accentEmotional: '#8b5cf6',
    accentProof: '#ff3b5c',
    border: '#1e2a3d',
    borderSubtle: '#142033',
    borderStrong: '#2e3f5c',
    glow: '#5debff',
    warning: '#eab308',
    success: '#22c55e',
    selection: '#5debff',
  },
  typography: defaultTypography,
  typographySystem: getTypographySystemForTheme('nocturnal-signal'),
  spacing: {
    baseUnit: 8,
    sectionY: '112px',
    containerX: 'clamp(24px, 6vw, 96px)',
    cardPadding: '24px',
    gridGap: '16px',
    density: 'cinematic',
  },
  radius: { xs: '2px', sm: '4px', md: '8px', lg: '12px', card: '2px', button: '2px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #5debff', dividerOpacity: 0.76 },
  elevation: {
    ambient: '0 16px 64px color-mix(in srgb, #05070d 76%, transparent)',
    raised: '0 16px 56px color-mix(in srgb, #2f6bff 10%, transparent)',
    glow: '0 0 24px color-mix(in srgb, #5debff 14%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #eaf0ff 6%, transparent)',
    card: '0 14px 40px color-mix(in srgb, #05070d 34%, transparent)',
  },
  background: {
    type: 'trace-grid',
    dotSize: 1,
    dotSpacing: 34,
    dotOpacity: 0.045,
    dotRevealOpacity: 0.11,
    dotFieldOpacity: 0.52,
    radialGlowColor: '#5debff',
    radialGlowOpacity: 0.055,
    radialGlowSize: 28,
    radialGlowBlur: 44,
    radialGlowColor2: '#2f6bff',
    radialGlowOpacity2: 0.08,
    noiseOpacity: 0,
    vignetteOpacity: 0.88,
    animationSpeed: 56,
    animationIntensity: 0.55,
    scanlineOpacity: 0.01,
    skylineOpacity: 0,
    textureOpacity: 0.02,
  },
  glow: { primary: '#2f6bff', secondary: '#5debff', intensity: 1, blur: '44px', spread: '28vmax' },
  motion: {
    personality: 'restrained',
    revealType: 'translateY',
    revealDuration: 480,
    hoverDuration: 140,
    transitionDuration: 220,
    complexDuration: 360,
    easingEnter: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easingExit: 'cubic-bezier(0.4, 0, 1, 1)',
    easingState: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    parallaxIntensity: 0,
    ambientMotionIntensity: 0.55,
  },
  components: {
    cardStyle: 'glass',
    buttonStyle: 'signal',
    navStyle: 'sticky-glass',
    caseFileStyle: 'case-file',
    badgeStyle: 'mono-trace',
    inputStyle: 'terminal',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 76%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-default) 84%, transparent)',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 78%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 36%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 56%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 82%, transparent)',
  },
  layout: {
    density: 'cinematic',
    maxContentWidth: '1248px',
    sectionPaddingTop: '112px',
    sectionPaddingBottom: '112px',
    cardPadding: '24px',
    gridGap: '16px',
    borderRadius: '2px',
    panelBlur: 16,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '80px',
    twelveColumnGap: '16px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'cold boot cinematic interface', intensity: 1, backgroundIntensity: 1 },
    projects: { mood: 'case files under blue trace light', intensity: 0.92, backgroundIntensity: 1 },
    proof: { mood: 'black-box inspection panel', intensity: 1, backgroundIntensity: 0.9, accent: '#ff3b5c' },
  },
  preview: {
    vibeLabel: 'Original signal',
    bestFor: 'Main default portfolio',
    densityLabel: 'Cinematic',
    motionLabel: 'Slow reveal',
    swatches: ['#05070d', '#101826', '#2f6bff', '#5debff', '#eaf0ff'],
    gradient: 'linear-gradient(135deg, #05070d 0%, #0b111c 45%, #112a56 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
