import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const noirOperatingSystem = defineTheme({
  id: 'noir-operating-system',
  name: 'Noir Operating System',
  shortDescription: 'Monochrome evidence OS with red proof markers.',
  emotionalTone: 'Investigative, sharp, monochrome, serious, cinematic noir.',
  designKeywords: ['detective OS', 'case files', 'evidence', 'silver type', 'red proof markers'],
  source: 'built-in',
  colors: {
    bg: '#030303',
    bgSecondary: '#0a0a0b',
    surface: '#101012',
    surfaceElevated: '#17171a',
    text: '#f3f3f0',
    textSecondary: '#c2c2bd',
    textMuted: '#7e7e78',
    accent: '#d8d8d2',
    accentSecondary: '#ffffff',
    accentEmotional: '#8b8b84',
    accentProof: '#ff3f4d',
    border: '#2b2b2c',
    borderSubtle: '#1d1d1e',
    borderStrong: '#555552',
    glow: '#ffffff',
    warning: '#d6b45f',
    success: '#a8d7b4',
    selection: '#ff3f4d',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Arial Narrow", "Inter", sans-serif',
    headingWeight: 700,
    bodyWeight: 400,
    lineHeight: 1.58,
    type2xl: 'clamp(2.4rem, 5vw, 4.25rem)',
    typeDisplay: 'clamp(3.8rem, 10vw, 8rem)',
  },
  typographySystem: getTypographySystemForTheme('noir-operating-system'),
  spacing: {
    baseUnit: 8,
    sectionY: '112px',
    containerX: 'clamp(24px, 5vw, 80px)',
    cardPadding: '22px',
    gridGap: '14px',
    density: 'balanced',
  },
  radius: { xs: '0px', sm: '0px', md: '2px', lg: '4px', card: '0px', button: '0px', pill: '0px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #ff3f4d', dividerOpacity: 0.9 },
  elevation: {
    ambient: '0 18px 68px color-mix(in srgb, #030303 80%, transparent)',
    raised: '0 18px 72px color-mix(in srgb, #000000 70%, transparent)',
    glow: '0 0 28px color-mix(in srgb, #ff3f4d 18%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #ffffff 6%, transparent)',
    card: '0 16px 44px color-mix(in srgb, #000000 52%, transparent)',
  },
  background: {
    type: 'noir-document',
    dotSize: 0.8,
    dotSpacing: 36,
    dotOpacity: 0.035,
    dotRevealOpacity: 0.06,
    dotFieldOpacity: 0.24,
    radialGlowColor: '#ffffff',
    radialGlowOpacity: 0.035,
    radialGlowSize: 22,
    radialGlowBlur: 36,
    radialGlowColor2: '#ff3f4d',
    radialGlowOpacity2: 0.055,
    noiseOpacity: 0.04,
    vignetteOpacity: 0.92,
    animationSpeed: 60,
    animationIntensity: 0.28,
    scanlineOpacity: 0.015,
    skylineOpacity: 0,
    textureOpacity: 0.08,
  },
  glow: { primary: '#ffffff', secondary: '#ff3f4d', intensity: 0.5, blur: '36px', spread: '22vmax' },
  motion: {
    personality: 'sharp',
    revealType: 'fadeIn',
    revealDuration: 420,
    hoverDuration: 110,
    transitionDuration: 190,
    complexDuration: 320,
    easingEnter: 'cubic-bezier(0.12, 0, 0.39, 0)',
    easingExit: 'cubic-bezier(0.61, 1, 0.88, 1)',
    easingState: 'cubic-bezier(0.33, 1, 0.68, 1)',
    parallaxIntensity: 0,
    ambientMotionIntensity: 0.25,
  },
  components: {
    cardStyle: 'case-file',
    buttonStyle: 'evidence',
    navStyle: 'case-index',
    caseFileStyle: 'case-file',
    badgeStyle: 'evidence-tag',
    inputStyle: 'ledger',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 88%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-strong) 58%, var(--line-default))',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 88%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-proof) 14%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-proof) 48%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 90%, transparent)',
  },
  layout: {
    density: 'balanced',
    maxContentWidth: '1180px',
    sectionPaddingTop: '112px',
    sectionPaddingBottom: '112px',
    cardPadding: '22px',
    gridGap: '14px',
    borderRadius: '0px',
    panelBlur: 10,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '74px',
    twelveColumnGap: '14px',
  },
  sectionMoodOverrides: {
    projects: { mood: 'evidence wall with open case files', intensity: 1, backgroundIntensity: 0.7, accent: '#ff3f4d' },
    proof: { mood: 'forensic proof ledger', intensity: 1, backgroundIntensity: 0.66, accent: '#ff3f4d' },
    timeline: { mood: 'indexed investigation trail', intensity: 0.9, backgroundIntensity: 0.58 },
  },
  preview: {
    vibeLabel: 'Evidence OS',
    bestFor: 'Proof-heavy credibility',
    densityLabel: 'Balanced',
    motionLabel: 'Sharp cuts',
    swatches: ['#030303', '#17171a', '#f3f3f0', '#7e7e78', '#ff3f4d'],
    gradient: 'linear-gradient(135deg, #030303 0%, #111113 72%, #3a1116 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
