import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const obsidianLab = defineTheme({
  id: 'obsidian-lab',
  name: 'Obsidian Lab',
  shortDescription: 'Private AI lab interface with modular dense surfaces.',
  emotionalTone: 'Experimental, technical, dense, powerful.',
  designKeywords: ['AI lab', 'skunkworks', 'obsidian surfaces', 'status lights', 'modular density'],
  source: 'built-in',
  colors: {
    bg: '#030807',
    bgSecondary: '#07100f',
    surface: '#0c1716',
    surfaceElevated: '#12211f',
    text: '#e9f7f2',
    textSecondary: '#a9beb7',
    textMuted: '#6d817b',
    accent: '#27d6a5',
    accentSecondary: '#57b8ff',
    accentEmotional: '#72f2d0',
    accentProof: '#ff6b4a',
    border: '#1d3531',
    borderSubtle: '#132522',
    borderStrong: '#38655d',
    glow: '#27d6a5',
    warning: '#e9c65f',
    success: '#4ff0b8',
    selection: '#27d6a5',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 650,
    bodyWeight: 400,
    lineHeight: 1.52,
    typeMd: '1.0625rem',
    typeLg: '1.375rem',
    typeXl: '1.875rem',
    type2xl: 'clamp(2.25rem, 4.6vw, 4rem)',
    typeDisplay: 'clamp(3.5rem, 9.4vw, 7.8rem)',
  },
  typographySystem: getTypographySystemForTheme('obsidian-lab'),
  spacing: {
    baseUnit: 8,
    sectionY: '104px',
    containerX: 'clamp(20px, 4.8vw, 76px)',
    cardPadding: '20px',
    gridGap: '12px',
    density: 'dense',
  },
  radius: { xs: '2px', sm: '3px', md: '5px', lg: '8px', card: '3px', button: '3px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #27d6a5', dividerOpacity: 0.82 },
  elevation: {
    ambient: '0 14px 60px color-mix(in srgb, #030807 80%, transparent)',
    raised: '0 20px 90px color-mix(in srgb, #27d6a5 12%, transparent)',
    glow: '0 0 34px color-mix(in srgb, #27d6a5 24%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #57b8ff 5%, transparent)',
    card: '0 14px 46px color-mix(in srgb, #030807 54%, transparent)',
  },
  background: {
    type: 'lab-grid',
    dotSize: 1,
    dotSpacing: 24,
    dotOpacity: 0.07,
    dotRevealOpacity: 0.12,
    dotFieldOpacity: 0.6,
    radialGlowColor: '#27d6a5',
    radialGlowOpacity: 0.07,
    radialGlowSize: 24,
    radialGlowBlur: 38,
    radialGlowColor2: '#57b8ff',
    radialGlowOpacity2: 0.08,
    noiseOpacity: 0.025,
    vignetteOpacity: 0.88,
    animationSpeed: 36,
    animationIntensity: 0.74,
    scanlineOpacity: 0.03,
    skylineOpacity: 0,
    textureOpacity: 0.04,
  },
  glow: { primary: '#27d6a5', secondary: '#57b8ff', intensity: 0.9, blur: '38px', spread: '24vmax' },
  motion: {
    personality: 'dense',
    revealType: 'translateY',
    revealDuration: 480,
    hoverDuration: 105,
    transitionDuration: 200,
    complexDuration: 340,
    easingEnter: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easingExit: 'cubic-bezier(0.4, 0, 1, 1)',
    easingState: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    parallaxIntensity: 0.02,
    ambientMotionIntensity: 0.72,
  },
  components: {
    cardStyle: 'lab',
    buttonStyle: 'lab',
    navStyle: 'lab-bar',
    caseFileStyle: 'lab',
    badgeStyle: 'status-chip',
    inputStyle: 'lab-control',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 86%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--accent-primary) 18%, var(--line-default))',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 88%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 22%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-primary) 52%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 86%, transparent)',
  },
  layout: {
    density: 'dense',
    maxContentWidth: '1188px',
    sectionPaddingTop: '104px',
    sectionPaddingBottom: '104px',
    cardPadding: '20px',
    gridGap: '12px',
    borderRadius: '3px',
    panelBlur: 12,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '72px',
    twelveColumnGap: '12px',
  },
  sectionMoodOverrides: {
    stack: { mood: 'modular lab control surface', intensity: 1, backgroundIntensity: 0.88 },
    projects: { mood: 'private build benches', intensity: 0.94, backgroundIntensity: 0.8 },
    proof: { mood: 'status-light reliability grid', intensity: 0.95, backgroundIntensity: 0.78, accent: '#27d6a5' },
  },
  preview: {
    vibeLabel: 'Private AI lab',
    bestFor: 'Engineer and founder audience',
    densityLabel: 'Dense',
    motionLabel: 'Fast controls',
    swatches: ['#030807', '#12211f', '#27d6a5', '#57b8ff', '#e9f7f2'],
    gradient: 'linear-gradient(145deg, #030807 0%, #0d1817 50%, #12372f 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
