import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const proofArchive = defineTheme({
  id: 'proof-archive',
  name: 'Proof Archive',
  shortDescription: 'Structured archive of receipts, logs, tags, and indexed systems.',
  emotionalTone: 'Structured, archival, trustworthy, exact.',
  designKeywords: ['archive', 'receipts', 'documentation', 'indexed sections', 'build logs'],
  source: 'built-in',
  colors: {
    bg: '#050505',
    bgSecondary: '#0d0d0d',
    surface: '#121212',
    surfaceElevated: '#1a1a1a',
    text: '#e6e6e6',
    textSecondary: '#b3b3b3',
    textMuted: '#666666',
    accent: '#cccccc',
    accentSecondary: '#ffffff',
    accentEmotional: '#808080',
    accentProof: '#ffffff',
    border: '#262626',
    borderSubtle: '#161616',
    borderStrong: '#404040',
    glow: '#ffffff',
    warning: '#808080',
    success: '#ffffff',
    selection: '#ffffff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    bodyFont: '"Inter", "Geist", "Segoe UI", sans-serif',
    monoFont: '"JetBrains Mono", "IBM Plex Mono", "SFMono-Regular", Consolas, monospace',
    baseFontSize: '16px',
    headingWeight: 650,
    bodyWeight: 400,
    lineHeight: 1.68,
    type2xl: 'clamp(2.3rem, 4.8vw, 4.2rem)',
    typeDisplay: 'clamp(3.6rem, 9.5vw, 7.6rem)',
  },
  typographySystem: getTypographySystemForTheme('proof-archive'),
  spacing: {
    baseUnit: 8,
    sectionY: '112px',
    containerX: 'clamp(22px, 5.2vw, 84px)',
    cardPadding: '24px',
    gridGap: '14px',
    density: 'balanced',
  },
  radius: { xs: '1px', sm: '2px', md: '4px', lg: '6px', card: '2px', button: '2px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #ffffff', dividerOpacity: 0.84 },
  elevation: {
    ambient: '0 16px 64px color-mix(in srgb, #050505 76%, transparent)',
    raised: '0 20px 80px color-mix(in srgb, #b3b3b3 10%, transparent)',
    glow: '0 0 32px color-mix(in srgb, #ffffff 12%, transparent)',
    inset: 'inset 0 1px 0 color-mix(in srgb, #ffffff 5%, transparent)',
    card: '0 16px 48px color-mix(in srgb, #050505 44%, transparent)',
  },
  background: {
    type: 'archive',
    dotSize: 0.75,
    dotSpacing: 38,
    dotOpacity: 0.04,
    dotRevealOpacity: 0.06,
    dotFieldOpacity: 0.3,
    radialGlowColor: '#ffffff',
    radialGlowOpacity: 0.015,
    radialGlowSize: 24,
    radialGlowBlur: 42,
    radialGlowColor2: '#808080',
    radialGlowOpacity2: 0.02,
    noiseOpacity: 0.04,
    vignetteOpacity: 0.85,
    animationSpeed: 72,
    animationIntensity: 0.26,
    scanlineOpacity: 0,
    skylineOpacity: 0,
    textureOpacity: 0.075,
  },
  glow: { primary: '#ffffff', secondary: '#cccccc', intensity: 0.24, blur: '42px', spread: '24vmax' },
  motion: {
    personality: 'archival',
    revealType: 'fadeIn',
    revealDuration: 440,
    hoverDuration: 110,
    transitionDuration: 210,
    complexDuration: 330,
    easingEnter: 'cubic-bezier(0.33, 1, 0.68, 1)',
    easingExit: 'cubic-bezier(0.32, 0, 0.67, 0)',
    easingState: 'cubic-bezier(0.33, 1, 0.68, 1)',
    parallaxIntensity: 0,
    ambientMotionIntensity: 0.18,
  },
  components: {
    cardStyle: 'archive',
    buttonStyle: 'archive',
    navStyle: 'case-index',
    caseFileStyle: 'archive',
    badgeStyle: 'archive-tag',
    inputStyle: 'archive-field',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 84%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-strong) 42%, var(--line-default))',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 84%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 16%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 38%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 86%, transparent)',
  },
  layout: {
    density: 'balanced',
    maxContentWidth: '1168px',
    sectionPaddingTop: '112px',
    sectionPaddingBottom: '112px',
    cardPadding: '24px',
    gridGap: '14px',
    borderRadius: '2px',
    panelBlur: 8,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '74px',
    twelveColumnGap: '14px',
  },
  sectionMoodOverrides: {
    projects: { mood: 'inspectable records and receipts', intensity: 1, backgroundIntensity: 0.64 },
    proof: { mood: 'indexed proof table', intensity: 1, backgroundIntensity: 0.62, accent: '#e06a5f' },
    timeline: { mood: 'chronological build archive', intensity: 0.92, backgroundIntensity: 0.58 },
  },
  preview: {
    vibeLabel: 'Receipt archive',
    bestFor: 'Hiring proof inspection',
    densityLabel: 'Indexed',
    motionLabel: 'Minimal',
    swatches: ['#070b10', '#1c2630', '#eef1e9', '#8db3d9', '#e06a5f'],
    gradient: 'linear-gradient(145deg, #070b10 0%, #151c25 64%, #26323a 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
