import { defineTheme, defaultTypography, themeTimestamp } from './_shared';
import { getTypographySystemForTheme } from '../../utils/textEffects';

export const quantumRain = defineTheme({
  id: 'quantum-rain',
  name: 'Quantum Rain',
  shortDescription: 'Cosmic rain field with cyan-violet scientific atmosphere.',
  emotionalTone: 'Cosmic, scientific, poetic, atmospheric.',
  designKeywords: ['space', 'quantum physics', 'rain', 'orbital traces', 'violet glow'],
  source: 'built-in',
  colors: {
    bg: '#020615',
    bgSecondary: '#071022',
    surface: '#0a162b',
    surfaceElevated: '#0e1c35',
    text: '#ecf5ff',
    textSecondary: '#a8bad4',
    textMuted: '#6f82a2',
    accent: '#34a4ff',
    accentSecondary: '#73f7ff',
    accentEmotional: '#9b7cff',
    accentProof: '#ff5c9a',
    border: '#1a3151',
    borderSubtle: '#10233d',
    borderStrong: '#2f5f91',
    glow: '#73f7ff',
    warning: '#ffd166',
    success: '#66f6c5',
    selection: '#73f7ff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 650,
    lineHeight: 1.66,
    typeLg: '1.625rem',
    type2xl: 'clamp(2.6rem, 5.6vw, 4.9rem)',
    typeDisplay: 'clamp(4rem, 10.8vw, 8.8rem)',
  },
  typographySystem: getTypographySystemForTheme('quantum-rain'),
  spacing: {
    baseUnit: 8,
    sectionY: '136px',
    containerX: 'clamp(24px, 7vw, 104px)',
    cardPadding: '28px',
    gridGap: '20px',
    density: 'cinematic',
  },
  radius: { xs: '3px', sm: '6px', md: '12px', lg: '18px', card: '8px', button: '6px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #73f7ff', dividerOpacity: 0.64 },
  elevation: {
    ambient: '0 18px 86px color-mix(in srgb, #020615 72%, transparent)',
    raised: '0 28px 110px color-mix(in srgb, #34a4ff 16%, transparent)',
    glow: '0 0 56px color-mix(in srgb, #9b7cff 22%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #73f7ff 7%, transparent)',
    card: '0 20px 80px color-mix(in srgb, #020615 50%, transparent)',
  },
  background: {
    type: 'starfield',
    dotSize: 1.2,
    dotSpacing: 28,
    dotOpacity: 0.1,
    dotRevealOpacity: 0.2,
    dotFieldOpacity: 0.78,
    radialGlowColor: '#73f7ff',
    radialGlowOpacity: 0.11,
    radialGlowSize: 34,
    radialGlowBlur: 58,
    radialGlowColor2: '#9b7cff',
    radialGlowOpacity2: 0.14,
    noiseOpacity: 0.025,
    vignetteOpacity: 0.84,
    animationSpeed: 82,
    animationIntensity: 0.9,
    scanlineOpacity: 0.01,
    skylineOpacity: 0,
    textureOpacity: 0.035,
  },
  glow: { primary: '#34a4ff', secondary: '#9b7cff', intensity: 1.15, blur: '58px', spread: '34vmax' },
  motion: {
    personality: 'atmospheric',
    revealType: 'translateY',
    revealDuration: 760,
    hoverDuration: 150,
    transitionDuration: 340,
    complexDuration: 500,
    easingEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
    easingExit: 'cubic-bezier(0.55, 0.06, 0.68, 0.19)',
    easingState: 'cubic-bezier(0.22, 1, 0.36, 1)',
    parallaxIntensity: 0.16,
    ambientMotionIntensity: 1.35,
  },
  components: {
    cardStyle: 'cosmic',
    buttonStyle: 'cosmic',
    navStyle: 'sticky-glass',
    caseFileStyle: 'cosmic',
    badgeStyle: 'orbital',
    inputStyle: 'cosmic-console',
    cardBackground: 'linear-gradient(145deg, color-mix(in srgb, var(--surface-card) 82%, transparent), color-mix(in srgb, var(--accent-emotional) 7%, transparent))',
    cardBorder: 'color-mix(in srgb, var(--accent-secondary) 20%, var(--line-default))',
    cardHoverBackground: 'linear-gradient(145deg, color-mix(in srgb, var(--surface-raised) 84%, transparent), color-mix(in srgb, var(--accent-emotional) 10%, transparent))',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 30%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 58%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 78%, transparent)',
  },
  layout: {
    density: 'cinematic',
    maxContentWidth: '1280px',
    sectionPaddingTop: '136px',
    sectionPaddingBottom: '136px',
    cardPadding: '28px',
    gridGap: '20px',
    borderRadius: '8px',
    panelBlur: 20,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '82px',
    twelveColumnGap: '20px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'deep-space rain signal', intensity: 1, backgroundIntensity: 1 },
    human: { mood: 'poetic blue atmosphere', intensity: 1, backgroundIntensity: 1, accent: '#9b7cff' },
    stack: { mood: 'scientific cluster map', intensity: 0.94, backgroundIntensity: 0.9 },
  },
  preview: {
    vibeLabel: 'Cosmic rain',
    bestFor: 'Most immersive version',
    densityLabel: 'Cinematic',
    motionLabel: 'Slow parallax',
    swatches: ['#020615', '#0e1c35', '#34a4ff', '#9b7cff', '#73f7ff'],
    gradient: 'radial-gradient(circle at 30% 30%, #173a68 0%, #071022 42%, #020615 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});
