import { defineTheme, defaultTypography, themeTimestamp } from './_shared';

export const skylineTerminal = defineTheme({
  id: 'skyline-terminal',
  name: 'Skyline Terminal',
  shortDescription: 'Late-night city terminal with electric blue ambition lines.',
  emotionalTone: 'Urban, ambitious, lonely-but-focused, modern.',
  designKeywords: ['city skyline', 'terminal glow', 'night builder', 'electric blue', 'professional edge'],
  source: 'built-in',
  colors: {
    bg: '#05080b',
    bgSecondary: '#0c1116',
    surface: '#111820',
    surfaceElevated: '#16202a',
    text: '#eef6ff',
    textSecondary: '#a9b7c7',
    textMuted: '#748292',
    accent: '#1677ff',
    accentSecondary: '#26d9ff',
    accentEmotional: '#5f8cff',
    accentProof: '#ff6550',
    border: '#203040',
    borderSubtle: '#172330',
    borderStrong: '#385267',
    glow: '#26d9ff',
    warning: '#f6b95d',
    success: '#63dcae',
    selection: '#26d9ff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 700,
    bodyWeight: 400,
    lineHeight: 1.58,
    type2xl: 'clamp(2.35rem, 4.8vw, 4.4rem)',
    typeDisplay: 'clamp(3.7rem, 9.8vw, 8.1rem)',
  },
  spacing: {
    baseUnit: 8,
    sectionY: '116px',
    containerX: 'clamp(22px, 5.6vw, 88px)',
    cardPadding: '24px',
    gridGap: '16px',
    density: 'balanced',
  },
  radius: { xs: '2px', sm: '4px', md: '6px', lg: '10px', card: '3px', button: '3px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #26d9ff', dividerOpacity: 0.72 },
  elevation: {
    ambient: '0 16px 64px color-mix(in srgb, #05080b 78%, transparent)',
    raised: '0 22px 82px color-mix(in srgb, #1677ff 15%, transparent)',
    glow: '0 0 34px color-mix(in srgb, #26d9ff 26%, transparent)',
    inset: 'inset 0 0 0 1px color-mix(in srgb, #eef6ff 5%, transparent)',
    card: '0 16px 58px color-mix(in srgb, #05080b 52%, transparent)',
  },
  background: {
    type: 'skyline',
    dotSize: 1,
    dotSpacing: 30,
    dotOpacity: 0.065,
    dotRevealOpacity: 0.13,
    dotFieldOpacity: 0.56,
    radialGlowColor: '#26d9ff',
    radialGlowOpacity: 0.075,
    radialGlowSize: 26,
    radialGlowBlur: 42,
    radialGlowColor2: '#1677ff',
    radialGlowOpacity2: 0.1,
    noiseOpacity: 0.018,
    vignetteOpacity: 0.86,
    animationSpeed: 38,
    animationIntensity: 0.85,
    scanlineOpacity: 0.045,
    skylineOpacity: 0.16,
    textureOpacity: 0.025,
  },
  glow: { primary: '#1677ff', secondary: '#26d9ff', intensity: 1.05, blur: '42px', spread: '26vmax' },
  motion: {
    personality: 'scanline',
    revealType: 'translateY',
    revealDuration: 560,
    hoverDuration: 120,
    transitionDuration: 230,
    complexDuration: 380,
    easingEnter: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    easingExit: 'cubic-bezier(0.4, 0, 1, 1)',
    easingState: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
    parallaxIntensity: 0.08,
    ambientMotionIntensity: 0.95,
  },
  components: {
    cardStyle: 'terminal',
    buttonStyle: 'console',
    navStyle: 'terminal-rail',
    caseFileStyle: 'terminal',
    badgeStyle: 'terminal-status',
    inputStyle: 'terminal',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 82%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--accent-primary) 16%, var(--line-default))',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 84%, transparent)',
    buttonBackground: 'color-mix(in srgb, var(--accent-primary) 34%, var(--surface-raised))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 50%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 84%, transparent)',
  },
  layout: {
    density: 'balanced',
    maxContentWidth: '1220px',
    sectionPaddingTop: '116px',
    sectionPaddingBottom: '116px',
    cardPadding: '24px',
    gridGap: '16px',
    borderRadius: '3px',
    panelBlur: 14,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '76px',
    twelveColumnGap: '16px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'night skyline boot sequence', intensity: 0.95, backgroundIntensity: 0.96 },
    stack: { mood: 'terminal modules with city glow', intensity: 0.9, backgroundIntensity: 0.82 },
    contact: { mood: 'open channel across a city network', intensity: 0.86, backgroundIntensity: 0.78 },
  },
  preview: {
    vibeLabel: 'Night builder',
    bestFor: 'Career-facing edge',
    densityLabel: 'Balanced',
    motionLabel: 'Scanline glow',
    swatches: ['#05080b', '#16202a', '#1677ff', '#26d9ff', '#eef6ff'],
    gradient: 'linear-gradient(160deg, #05080b 0%, #0f1720 58%, #093261 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});

