import { defineTheme, defaultTypography, themeTimestamp } from './_shared';

export const softTraceLuxury = defineTheme({
  id: 'soft-trace-luxury',
  name: 'Soft Trace Luxury',
  shortDescription: 'Editorial luxury restraint with pearl-blue engineering traces.',
  emotionalTone: 'Expensive, quiet, spacious, controlled.',
  designKeywords: ['luxury fashion', 'negative space', 'pearl blue', 'soft contrast', 'editorial proof'],
  source: 'built-in',
  colors: {
    bg: '#07090f',
    bgSecondary: '#10141d',
    surface: '#121720',
    surfaceElevated: '#171d28',
    text: '#f0f4fb',
    textSecondary: '#bec7d7',
    textMuted: '#858fa2',
    accent: '#8fb8ff',
    accentSecondary: '#c7f2ff',
    accentEmotional: '#c4a7ff',
    accentProof: '#f06f86',
    border: '#263142',
    borderSubtle: '#1b2432',
    borderStrong: '#3b4658',
    glow: '#c7f2ff',
    warning: '#e8c66b',
    success: '#8be6be',
    selection: '#c7f2ff',
  },
  typography: {
    ...defaultTypography,
    displayFont: '"Space Grotesk", "Inter", "Segoe UI", sans-serif',
    headingWeight: 600,
    bodyWeight: 400,
    lineHeight: 1.72,
    type2xl: 'clamp(2.75rem, 5.8vw, 5.25rem)',
    typeDisplay: 'clamp(4.25rem, 11vw, 9rem)',
  },
  spacing: {
    baseUnit: 8,
    sectionY: '152px',
    containerX: 'clamp(28px, 8vw, 120px)',
    cardPadding: '32px',
    gridGap: '24px',
    density: 'editorial',
  },
  radius: { xs: '2px', sm: '6px', md: '10px', lg: '16px', card: '6px', button: '999px', pill: '999px' },
  borders: { hairline: '1px', default: '1px', strong: '1px', focus: '2px solid #c7f2ff', dividerOpacity: 0.54 },
  elevation: {
    ambient: '0 24px 96px color-mix(in srgb, #07090f 70%, transparent)',
    raised: '0 30px 110px color-mix(in srgb, #8fb8ff 10%, transparent)',
    glow: '0 0 48px color-mix(in srgb, #c7f2ff 14%, transparent)',
    inset: 'inset 0 1px 0 color-mix(in srgb, #f0f4fb 7%, transparent)',
    card: '0 22px 72px color-mix(in srgb, #07090f 42%, transparent)',
  },
  background: {
    type: 'soft-luxury',
    dotSize: 0.8,
    dotSpacing: 48,
    dotOpacity: 0.04,
    dotRevealOpacity: 0.08,
    dotFieldOpacity: 0.36,
    radialGlowColor: '#c7f2ff',
    radialGlowOpacity: 0.055,
    radialGlowSize: 34,
    radialGlowBlur: 68,
    radialGlowColor2: '#8fb8ff',
    radialGlowOpacity2: 0.06,
    noiseOpacity: 0.015,
    vignetteOpacity: 0.76,
    animationSpeed: 68,
    animationIntensity: 0.45,
    scanlineOpacity: 0,
    skylineOpacity: 0,
    textureOpacity: 0.02,
  },
  glow: { primary: '#8fb8ff', secondary: '#c7f2ff', intensity: 0.55, blur: '68px', spread: '34vmax' },
  motion: {
    personality: 'minimal',
    revealType: 'fadeIn',
    revealDuration: 560,
    hoverDuration: 150,
    transitionDuration: 320,
    complexDuration: 460,
    easingEnter: 'cubic-bezier(0.16, 1, 0.3, 1)',
    easingExit: 'cubic-bezier(0.7, 0, 0.84, 0)',
    easingState: 'cubic-bezier(0.16, 1, 0.3, 1)',
    parallaxIntensity: 0,
    ambientMotionIntensity: 0.4,
  },
  components: {
    cardStyle: 'quiet-luxury',
    buttonStyle: 'luxury',
    navStyle: 'quiet-strip',
    caseFileStyle: 'quiet-luxury',
    badgeStyle: 'pearl-index',
    inputStyle: 'quiet',
    cardBackground: 'color-mix(in srgb, var(--surface-card) 64%, transparent)',
    cardBorder: 'color-mix(in srgb, var(--line-default) 62%, transparent)',
    cardHoverBackground: 'color-mix(in srgb, var(--surface-raised) 70%, transparent)',
    buttonBackground: 'linear-gradient(135deg, color-mix(in srgb, var(--accent-primary) 24%, var(--surface-raised)), color-mix(in srgb, var(--accent-secondary) 10%, var(--surface-raised)))',
    buttonBorder: 'color-mix(in srgb, var(--accent-secondary) 42%, var(--line-default))',
    navBackground: 'color-mix(in srgb, var(--surface-base) 74%, transparent)',
  },
  layout: {
    density: 'editorial',
    maxContentWidth: '1320px',
    sectionPaddingTop: '152px',
    sectionPaddingBottom: '152px',
    cardPadding: '32px',
    gridGap: '24px',
    borderRadius: '6px',
    panelBlur: 22,
    navPosition: 'sticky',
    heroHeight: 'auto',
    sectionAlignment: 'left',
    headerHeight: '88px',
    twelveColumnGap: '24px',
  },
  sectionMoodOverrides: {
    hero: { mood: 'quiet fashion campaign with engineered restraint', intensity: 0.82, backgroundIntensity: 0.72 },
    projects: { mood: 'premium dossier gallery', intensity: 0.76, backgroundIntensity: 0.62 },
    human: { mood: 'soft human blue light', intensity: 0.88, backgroundIntensity: 0.72, accent: '#c7f2ff' },
  },
  preview: {
    vibeLabel: 'Recruiter-safe luxury',
    bestFor: 'Premium career version',
    densityLabel: 'Spacious',
    motionLabel: 'Minimal fade',
    swatches: ['#07090f', '#171d28', '#8fb8ff', '#c7f2ff', '#f0f4fb'],
    gradient: 'linear-gradient(135deg, #07090f 0%, #141b27 52%, #263f61 100%)',
  },
  createdAt: themeTimestamp,
  updatedAt: themeTimestamp,
});

